### ISSUE TITLE
Randomized Grid Search

### ISSUE THREAD

**Issue by jlevy44** [cgnorthcutt/hypopt#6]
Does hypopt perform randomized grid search? If not, I may make a PR. It's taking a bit too long for me to perform a coarse grid search. Thanks!

**Comment by cgnorthcutt** [comment]
Not currently, no. It was an intentional choice because most users don't realize that RandomizedCV does exactly the thing but just stops early and has less coverage and might actually miss the global optima. Please do make a PR and I'm happy to include, but it needs to be implemented separately from GridSearchCV (not as an early_stopping parameter).

**Comment by jlevy44** [comment]
Okay great. Thanks!

**Comment by jlevy44** [comment]
It would also be nice to have a Bayesian hyperparameter optimization method. That may get closer to the global optima. I wonder if there's a way to integrate this with skopt. What are your thoughts?

**Comment by cgnorthcutt** [comment]
Follow up in this pull request https://github.com/cgnorthcutt/hypopt/pull/7
