### ISSUE TITLE
Link to PyTorch example 404

### ISSUE THREAD

**Issue by BramVanroy** [cgnorthcutt/hypopt#8]
The link in the ReadME that should lead to the PyTorch example is dead, unfortunately.

I can't find any references to hypopt [here](https://github.com/cgnorthcutt/cleanlab/blob/master/cleanlab/models/mnist_pytorch.py) so I don't think that's the correct one.

**Comment by cgnorthcutt** [comment]
Hi thanks for pointing this out. I've updated the links. Note that the examples do not use hypopt, they just show you how to wrap your CNN for compliance with hypopt. Code demonstrating how to use PyTorch with hypopt looks exactly like using scikit-learn with hypopt. You:
1.  wrap your class/model in a scikit-learn wrapper.
2. use an object instance of that class with hypopt just like the scikit-learn examples.

Closing, feel free to open another if your issue is not resolved.
